server:
  port: 8080

spring:
  application:
    name: cab_booking_system
  datasource:
    url: jdbc:mysql://localhost:3306/cab_booking_app_db
    username: root
    password: 'root'
    driverClassName: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


